baseURL = 'https://kipplesunderscore.github.io/'
languageCode = 'en-us'
title = 'kipplesunderscore'
theme = "ananke"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/kipplesunderscore"
[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/tim-kipling-45a5a31a9/"
